RegisterNetEvent('Switcher:SwitchToEditor')
AddEventHandler('Switcher:SwitchToEditor', function()
    print('start CNC Editor')
    -- ExecuteCommand('add_ace builtin.everyone "vMenu.Everything" allow')
    StopResource('vSync')
    exports.mapmanager:changeGameType('cnceditor')
end)

RegisterNetEvent('Switcher:SwitchToCNC')
AddEventHandler('Switcher:SwitchToCNC', function()
    print('start CNC')
    exports.mapmanager:changeGameType('cnc')
    Citizen.Wait(1000)
    -- ExecuteCommand('remove_ace builtin.everyone "vMenu.Everything" allow')
    -- StartResource('editorhud')
    StartResource('vSync')
    StopResource('editorhud')
    StopResource('vMenu')

end)